/**
 * This file contains any types or enums returned from the Google API.
 */

 export enum GMBStarRating {
  STAR_RATING_UNSPECIFIED,
  ONE,
  TWO,
  THREE,
  FOUR,
  FIVE
 }

 export enum GMBAuthorType {
  AUTHOR_TYPE_UNSPECIFIED = 'AUTHOR_TYPE_UNSPECIFIED',
  REGULAR_USER = 'REGULAR_USER',
  LOCAL_GUIDE = 'LOCAL_GUIDE',
  MERCHANT = 'MERCHANT'
 }

 export enum GMBUserAccountTypes {
   ACCOUNT_TYPE_UNSPECIFIED = 'ACCOUNT_TYPE_UNSPECIFIED',
   PERSONAL = 'PERSONAL',
   LOCATION_GROUP = 'LOCATION_GROUP',
   USER_GROUP = 'USER_GROUP',
   ORGANIZATION = 'ORGANIZATION'
 }

 export enum GMBApiActionTypes {
   GET_ACCOUNTS = 'GET_ACCOUNTS',
   GET_LOCATIONS_FOR_ACCOUNT = 'GET_LOCATIONS_FOR_ACCOUNT',
   POST_LOCATION_MEDIA = 'POST_LOCATION_MEDIA',
   DELETE_LOCATION_MEDIA = 'DELETE_LOCATION_MEDIA',
   POST_MEDIA_DATA_REF = 'POST_MEDIA_DATA_REF',
   POST_MEDIA = 'POST_MEDIA',
   GET_LOCAL_POSTS = 'GET_LOCAL_POSTS',
   GET_LOCAL_POSTS_INSIGHT = 'GET_LOCAL_POSTS_INSIGHT',
   GET_LOCAL_POST_BY_ID = 'GET_LOCAL_POST_BY_ID',
   POST_LOCAL_POST = 'POST_LOCAL_POST',
   PATCH_LOCAL_POST = 'PATCH_LOCAL_POST',
   GET_REVIEWS = 'GET_REVIEWS',
   GET_STARTING_REVIEWS = 'GET_STARTING_REVIEWS',
   PUT_REVIEW_REPLY = 'PUT_REVIEW_REPLY',
   DELETE_REVIEW_REPLY = 'DELETE_REVIEW_REPLY',
   GET_QUESTIONS = 'GET_QUESTIONS',
   GET_STARTING_QUESTIONS = 'GET_STARTING_QUESTIONS',
   PUT_QUESTION_REPLY = 'PUT_QUESTION_REPLY',
   DELETE_QUESTION_REPLY = 'DELETE_QUESTION_REPLY'
 }