name: Run tests for the APIs

env:
  GIT_LOCAL_BRANCH: ${{ github.sha }}

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Start db & server
        run: make run-test
      - name: Run test
        run: make run-server-test
      - name: Close containers
        run: make close-test
        if: ${{ always() }}
